name: Weeklu Update
description: Use this template for the daily update
title: XXX-XXX | NAME | Weekly report
labels:
  - weekly update
assignees:
  - kapravel
body:
  - type: markdown
    attributes:
      value: |
        ## What was done

        ### Milestone:

  - type: markdown
    attributes:
      value: |
        ## Up next

        ### Milestone:

  - type: markdown
    attributes:
      value: |
        ## Paper of the week: