name: Weekly Update V2
description: Template for the weekly report (yaml edition).
title: "XXX-XXX | NAME | PROJECT-NAME"
labels: ["weekly report"]
projects: ["rekap-ncsu/4"]
assignees:
  - kapravel
body:
  - type: textarea
    id: main-stuff
    attributes:
      label: Project Problem Statement
      description: Enter your milestones and issues attached to them
      value: | 
        PROBLEM STATEMENT HERE

        ### Sprint Goal
        
        ## What was done
        
        #### Milestone: MILESTONE

        ## Up next

        #### Milestone: MILESTONE

        ## Paper of the week:
    validations:
      required: true
