name: Weekly Update V2
description: Template for the weekly report (yaml edition).
title: "XXX-XXX | NAME | PROJECT-NAME"
labels: ["Weekly Update"]
projects: ["rekap progress report"]
assignees:
  - kapravel
body:
  - type: textarea
    id: main-stuff
    attributes:
      label: Content
      description: Enter your milestones and issues attached to them
      value: | 
        ## What was done
        
        ### Milestone:

        ## Up next

        ### Milestone:

        ## Paper of the week:
    validations:
      required: true
